<a href="https://colab.research.google.com/github/singurupavani2002/Singuru-Pavani/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. REMOVING DUPLICATES**

**Import Libraries**

In [ ]:
import pandas as pd

**Upload Your Dataset**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving CLEANED DATASET.xlsx to CLEANED DATASET.xlsx

**Load the Excel File**

In [ ]:
import pandas as pd
df = pd.read_excel("CLEANED DATASET.xlsx")

**View Data**

In [ ]:
df.head()

,show_id,type,cast,country,date_added,release_year,rating,duration,genre,movie_names
0,s388,TV Show,"Actor 1, Actor 237",India,2019-02-03 00:00:00,2015.0,2.0,1 Seasons,Romance,Inception
1,s474,Movie,"Actor 1, Actor 319",USA,2019-06-18 00:00:00,2002.0,5.0,84 min,Thriller,The Dark Knight
2,s211,TV Show,"Actor 1, Actor 357",India,2018-08-24 00:00:00,2002.0,6.0,5 Seasons,Documentary,Interstellar
3,s364,Movie,"Actor 10, Actor 238",USA,2015-04-04 00:00:00,2013.0,4.0,135 min,Drama,The Godfather
4,s623,Movie,"Actor 10, Actor 280",Australia,2013-10-16 00:00:00,2000.0,6.0,103 min,Drama,Pulp Fiction

**Check Duplicate Rows**

In [ ]:
df.duplicated().sum()

np.int64(0)

**Remove Duplicates**

In [ ]:
df_cleaned = df.drop_duplicates()

**2. DATA CLEANING**

**Import Library**

In [ ]:
import pandas as pd

**Upload Dataset**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving CLEANED DATASET.xlsx to CLEANED DATASET (1).xlsx

**Load Dataset**

In [ ]:
df = pd.read_excel("CLEANED DATASET.xlsx")

**View Data**

In [ ]:
df.head()

,show_id,type,cast,country,date_added,release_year,rating,duration,genre,movie_names
0,s388,TV Show,"Actor 1, Actor 237",India,2019-02-03 00:00:00,2015.0,2.0,1 Seasons,Romance,Inception
1,s474,Movie,"Actor 1, Actor 319",USA,2019-06-18 00:00:00,2002.0,5.0,84 min,Thriller,The Dark Knight
2,s211,TV Show,"Actor 1, Actor 357",India,2018-08-24 00:00:00,2002.0,6.0,5 Seasons,Documentary,Interstellar
3,s364,Movie,"Actor 10, Actor 238",USA,2015-04-04 00:00:00,2013.0,4.0,135 min,Drama,The Godfather
4,s623,Movie,"Actor 10, Actor 280",Australia,2013-10-16 00:00:00,2000.0,6.0,103 min,Drama,Pulp Fiction

**Check Missing Values**

In [ ]:
df.isnull().sum()

show_id         8
type            2
cast            8
country         8
date_added      3
release_year    8
rating          8
duration        2
genre           8
movie_names     8
dtype: int64

**Handle Missing Values**

In [ ]:
df = df.dropna()

In [ ]:
df = df.fillna("Unknown")

/tmp/ipykernel_13669/1544372002.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna("Unknown")

**Remove Duplicates**

In [ ]:
df = df.drop_duplicates()

**Rename Columns**

In [ ]:
df.columns = df.columns.str.strip().str.lower()

**Check Clean Data**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       99 non-null     object
 1   type          99 non-null     object
 2   cast          99 non-null     object
 3   country       99 non-null     object
 4   date_added    99 non-null     datetime64[ns]
 5   release_year  99 non-null     float64
 6   rating        99 non-null     float64
 7   duration      99 non-null     object
 8   genre         99 non-null     object
 9   movie_names   99 non-null     object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 8.5+ KB

**Save Cleaned Data**

In [ ]:
df.to_excel("cleaned_data.xlsx", index=False)

**3. DATA PREPARATION**

**Convert Date Column**

In [ ]:
df['date_added'] = pd.to_datetime(df['date_added'])

**Extract Year & Month**

In [ ]:
df['year_added'] = df['date_added'].dt.year

In [ ]:
df['month_added'] = df['date_added'].dt.month

**Create New Columns**

In [ ]:
df['duration_category'] = df['duration'].apply(lambda x: 'Short' if '90' in str(x) else 'Long')

**Group Data**

In [ ]:
df_grouped = df.groupby('genre')['show_id'].count()

**Sort Data**

In [ ]:
df = df.sort_values(by='release_year', ascending=False)

**Reset Index**

In [ ]:
df = df.reset_index(drop=True)

**Save Prepared Data**

In [ ]:
df.to_excel("prepared_data.xlsx", index=False)